import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { NextIntlClientProvider } from 'next-intl';
import { Geist, Geist_Mono } from 'next/font/google';

import { ReactQueryWrapper } from './forecast/provider/providers';
import { ClientLayout } from '../../components/layout';
import { ThemeSync } from '@/providers';

import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme')?.value;

  // const themeClass = themeCookie === 'dark' ? 'dark' : '';
  const themeClass = themeCookie === 'dark' ? 'dark' : 'dark';

  return (
    <html lang="en" className={themeClass}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <ReactQueryWrapper>
            <ThemeSync />
            <ClientLayout>{children}</ClientLayout>
          </ReactQueryWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
